services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - flaskapi_network

  db:
    image: postgres:15
    container_name: flaskapi_postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flaskapi_network

networks:
  flaskapi_network:

volumes:
  pgdata:
